name: Install OpenLane and Tools

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-env:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Clone OpenLane and setup
      - name: Clone and setup OpenLane
        run: |
          git clone https://github.com/VLSIDA/OpenRAM.git
          cd OpenRAM
          ./install_conda.sh
          ls > directory_listing.txt
          echo "Directory listing saved to directory_listing.txt"

      # Step 3: Display saved directory listing
      - name: Display directory listing
        run: |
          cd OpenRAM
          cat directory_listing.txt
