name: Install OpenRAM and Tools

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-env:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Clone OpenRAM and setup
      - name: Clone and setup OpenRAM
        run: |
          git clone https://github.com/VLSIDA/OpenRAM.git
          cd OpenRAM
          ./install_conda.sh
          ls > directory_listing.txt
          echo "Directory listing saved to directory_listing.txt"

      # Step 3: Define environment variables
      - name: Set environment variables
        run: |
          echo "export OPENRAM_HOME=$HOME/OpenRAM/compiler" >> $GITHUB_ENV
          echo "export OPENRAM_TECH=$HOME/OpenRAM/technology" >> $GITHUB_ENV
          echo "export PYTHONPATH=$OPENRAM_HOME" >> $GITHUB_ENV

      # Step 4: Display environment variables
      - name: Display environment variables
        run: |
          echo "OPENRAM_HOME: $OPENRAM_HOME"
          echo "OPENRAM_TECH: $OPENRAM_TECH"

