name: GDS File Processing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  view-gds:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install KLayout
      - name: Install KLayout
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://www.klayout.org/downloads/Ubuntu-22/klayout_0.28.6-1_amd64.deb
          sudo apt install -y ./klayout_0.28.6-1_amd64.deb

      # Step 3: Run the Ruby script with KLayout
      - name: Run KLayout Script
        run: |
          mkdir -p outputs
          klayout -b -r scripts/view_gds.rb -rd input_file=designs/example.gds -rd output_file=outputs/screenshot.png

      # Step 4: Upload the screenshot artifact
      - name: Upload GDS screenshot
        uses: actions/upload-artifact@v3
        with:
          name: gds-screenshot
          path: outputs/screenshot.png
